"""
Exports the trained Isolation Forest to a portable C header: flat arrays per
tree (feature index, threshold, left/right child, leaf sample count) plus a
scoring function template implementing the standard Isolation Forest anomaly
score, using only integer/float comparisons -- no floating-point matrix
multiplication, no ML framework or runtime dependency. This is the
"deployment preparation" step of the pipeline (telemetry -> dataset ->
preprocessing -> training -> evaluation -> anomaly detection -> deployment
preparation).

Status: Trained + Simulated only. This header has not been compiled or run on
any embedded target -- there is no hardware yet. Treat it as a starting point
for V1 firmware work, not a finished, verified artifact.

Score convention, stated explicitly because it's easy to get backwards: this
header implements the ORIGINAL Isolation Forest paper's convention
(Liu, Ting & Zhou 2008), s(x,n) = 2^(-E(h(x))/c(n)), where scores closer to
1.0 mean MORE anomalous and closer to 0.5 or below mean more normal. This is
the OPPOSITE sign convention from scikit-learn's `decision_function` (used in
ml/evaluate.py's report), where LOWER means more anomalous. Do not mix the two
without converting -- a direct numeric comparison between this header's score
and the evaluation report's numbers would be wrong.

Run: python ml/export_embedded.py
"""

import sys
from pathlib import Path

import joblib
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from ml.features import feature_columns  # noqa: E402

MODEL_PATH = Path("ml/models/isolation_forest_v1.joblib")
OUT_PATH = Path("firmware/inc/anomaly_model.h")


def average_path_length_c(n):
    """Standard Isolation Forest c(n): expected path length of an unsuccessful
    BST search over n points. n<=1 -> 0 (a single point needs no splits)."""
    if n <= 1:
        return 0.0
    if n == 2:
        return 1.0
    harmonic = np.log(n - 1) + 0.5772156649  # Euler-Mascheroni constant
    return 2.0 * harmonic - 2.0 * (n - 1) / n


def tree_arrays(tree):
    t = tree.tree_
    return {
        "feature": t.feature.astype(int).tolist(),
        "threshold": t.threshold.astype(float).tolist(),
        "left": t.children_left.astype(int).tolist(),
        "right": t.children_right.astype(int).tolist(),
        "n_node_samples": t.n_node_samples.astype(int).tolist(),
        "node_count": int(t.node_count),
    }


def emit_c_array(name, values, c_type):
    if c_type == "float":
        body = ", ".join(f"{v:.8f}f" for v in values)
    else:
        body = ", ".join(str(v) for v in values)
    return f"static const {c_type} {name}[] = {{{body}}};"


def generate_header(model, feature_names):
    trees = [tree_arrays(est) for est in model.estimators_]
    n_trees = len(trees)
    max_samples = getattr(model, "_max_samples", trees[0]["n_node_samples"][0])
    c_norm = average_path_length_c(max_samples)

    lines = []
    lines.append("/*")
    lines.append(" * Auto-generated by ml/export_embedded.py -- DO NOT EDIT BY HAND.")
    lines.append(f" * Source model: {MODEL_PATH}")
    lines.append(" * Status: Trained + Simulated only. Not compiled or run on any hardware yet.")
    lines.append(" *")
    lines.append(" * Score convention: original Isolation Forest paper (Liu, Ting, Zhou 2008),")
    lines.append(" * s(x,n) = 2^(-avg_path_length/c(n)). Closer to 1.0 = more anomalous.")
    lines.append(" * This is the OPPOSITE sign convention to scikit-learn's decision_function")
    lines.append(" * used in ml/evaluate.py's report -- do not compare the two numbers directly.")
    lines.append(" *")
    lines.append(f" * Feature vector expected by isolation_forest_score() below, IN THIS EXACT")
    lines.append(f" * ORDER ({len(feature_names)} features) -- this order comes from")
    lines.append(" * ml/features.py's feature_columns() and MUST be kept in sync with it:")
    for i, name in enumerate(feature_names):
        lines.append(f" *   [{i}] {name}")
    lines.append(" */")
    lines.append("#ifndef CUBESAT_ANOMALY_MODEL_H")
    lines.append("#define CUBESAT_ANOMALY_MODEL_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("#include <math.h>  /* logf, powf */")
    lines.append("")
    lines.append(f"#define ANOMALY_MODEL_N_FEATURES {len(feature_names)}")
    lines.append(f"#define ANOMALY_MODEL_N_TREES {n_trees}")
    lines.append(f"static const float ANOMALY_MODEL_C_NORM = {c_norm:.8f}f;")
    lines.append("")

    for i, tr in enumerate(trees):
        lines.append(f"/* --- tree {i}: {tr['node_count']} nodes --- */")
        lines.append(emit_c_array(f"tree{i}_feature", tr["feature"], "int16_t"))
        lines.append(emit_c_array(f"tree{i}_threshold", tr["threshold"], "float"))
        lines.append(emit_c_array(f"tree{i}_left", tr["left"], "int16_t"))
        lines.append(emit_c_array(f"tree{i}_right", tr["right"], "int16_t"))
        lines.append(emit_c_array(f"tree{i}_n_node_samples", tr["n_node_samples"], "int16_t"))
        lines.append("")

    lines.append("typedef struct {")
    lines.append("    const int16_t *feature;")
    lines.append("    const float *threshold;")
    lines.append("    const int16_t *left;")
    lines.append("    const int16_t *right;")
    lines.append("    const int16_t *n_node_samples;")
    lines.append("} IsolationTree_t;")
    lines.append("")
    lines.append(f"static const IsolationTree_t ANOMALY_MODEL_TREES[ANOMALY_MODEL_N_TREES] = {{")
    for i in range(n_trees):
        lines.append(f"    {{tree{i}_feature, tree{i}_threshold, tree{i}_left, tree{i}_right, tree{i}_n_node_samples}},")
    lines.append("};")
    lines.append("")
    lines.append("/* Standard Isolation Forest c(n): expected unsuccessful-BST-search path")
    lines.append(" * length for n points. Matches ml/export_embedded.py's average_path_length_c().")
    lines.append(" * Only called with n>=1 at runtime (leaf sample counts), so no n==0 case. */")
    lines.append("static float anomaly_model_c(float n) {")
    lines.append("    if (n <= 1.0f) return 0.0f;")
    lines.append("    if (n == 2.0f) return 1.0f;")
    lines.append("    float harmonic = logf(n - 1.0f) + 0.5772156649f;")
    lines.append("    return 2.0f * harmonic - 2.0f * (n - 1.0f) / n;")
    lines.append("}")
    lines.append("")
    lines.append("static float anomaly_model_tree_path_length(const IsolationTree_t *tree, const float *x) {")
    lines.append("    int16_t node = 0;")
    lines.append("    int16_t depth = 0;")
    lines.append("    while (tree->feature[node] >= 0) {  /* -2 marks a leaf */")
    lines.append("        int16_t f = tree->feature[node];")
    lines.append("        node = (x[f] <= tree->threshold[node]) ? tree->left[node] : tree->right[node];")
    lines.append("        depth++;")
    lines.append("    }")
    lines.append("    return (float)depth + anomaly_model_c((float)tree->n_node_samples[node]);")
    lines.append("}")
    lines.append("")
    lines.append("/* x must have ANOMALY_MODEL_N_FEATURES elements, in the exact order documented")
    lines.append(" * at the top of this file. Returns a score in roughly [0,1]; values closer to")
    lines.append(" * 1.0 indicate anomalous input (paper convention -- see file header). This")
    lines.append(" * function only latches FaultFlag.ML_ANOMALY through fdir's normal debounce")
    lines.append(" * gate; it must never be wired to directly change flight-computer mode. */")
    lines.append("static float isolation_forest_score(const float *x) {")
    lines.append("    float total_path_length = 0.0f;")
    lines.append("    for (int i = 0; i < ANOMALY_MODEL_N_TREES; i++) {")
    lines.append("        total_path_length += anomaly_model_tree_path_length(&ANOMALY_MODEL_TREES[i], x);")
    lines.append("    }")
    lines.append("    float avg_path_length = total_path_length / (float)ANOMALY_MODEL_N_TREES;")
    lines.append("    return powf(2.0f, -avg_path_length / ANOMALY_MODEL_C_NORM);")
    lines.append("}")
    lines.append("")
    lines.append("#endif /* CUBESAT_ANOMALY_MODEL_H */")
    return "\n".join(lines)


def main():
    model = joblib.load(MODEL_PATH)
    header = generate_header(model, feature_columns())
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(header)
    size_kb = len(header.encode()) / 1024
    print(f"wrote {OUT_PATH} ({size_kb:.1f} KB as C source text)")

    # Sanity check: thresholds should be plausible telemetry values, not garbage
    sample_thresholds = model.estimators_[0].tree_.threshold[:10]
    finite = sample_thresholds[sample_thresholds > -2]
    print(f"sample thresholds from tree 0 (sanity check, should look like plausible "
          f"feature values, not garbage): {finite[:5]}")


if __name__ == "__main__":
    main()
